name: Verify PRs for Auto Merge – Dry Run

on:
  schedule:
    - cron: '*/1 * * * *'  # every 10 minutes
  workflow_dispatch:

env:
  VERSION_LABEL: v1.0.0
  VERSION_BRANCH: developer
  REQUIRED_LABEL: ready-to-merge
  VERIFIED_LABEL: verified

jobs:
  verify-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh jq

      - name: Fetch all open PRs
        id: list-prs
        run: |
          prs=$(gh pr list --state open --json number --jq '.[] | .number')
          echo "prs<<EOF" >> $GITHUB_OUTPUT
          echo "$prs" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Process eligible PRs
        run: |
          for pr in ${{ steps.list-prs.outputs.prs }}; do
            echo "🔍 Checking PR #$pr..."

            base_branch=$(gh pr view $pr --json baseRefName --jq '.baseRefName')
            labels=$(gh pr view $pr --json labels --jq '.labels[].name')
            approved=$(gh pr view $pr --json reviewDecision --jq '.reviewDecision')
            resolved=$(gh pr view $pr --json reviewThreads --jq '[.reviewThreads[] | select(.isResolved == false)] | length == 0')
            mergeable=$(gh pr view $pr --json mergeable --jq '.mergeable')
            checks_passed=$(gh pr checks $pr --exit-status >/dev/null 2>&1 && echo true || echo false)

            echo "Base: $base_branch | Labels: $labels"
            echo "Approved: $approved | Resolved: $resolved | Mergeable: $mergeable | CI passed: $checks_passed"

            # Conditions
            if [[ "$base_branch" != "$VERSION_BRANCH" ]]; then
              echo "⏩ Skipping: wrong base branch"
              continue
            fi

            if ! echo "$labels" | grep -q "$VERSION_LABEL"; then
              echo "⏩ Skipping: missing version label"
              continue
            fi

            if ! echo "$labels" | grep -q "$REQUIRED_LABEL"; then
              echo "⏩ Skipping: missing ready-to-merge label"
              continue
            fi

            if [[ "$approved" != "APPROVED" ]]; then
              echo "⏩ Skipping: not approved"
              continue
            fi

            if [[ "$resolved" != "true" ]]; then
              echo "⏩ Skipping: unresolved threads"
              continue
            fi

            if [[ "$checks_passed" != "true" ]]; then
              echo "⏩ Skipping: CI failed or pending"
              continue
            fi

            if [[ "$mergeable" != "MERGEABLE" ]]; then
              echo "⏩ Skipping: not mergeable (may have conflicts)"
              continue
            fi

            echo "✅ PR #$pr meets all merge criteria – tagging with '${VERIFIED_LABEL}'"

            gh issue edit $pr --add-label "${VERIFIED_LABEL}"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
