name: Auto Merge Verified PRs

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minute
  workflow_dispatch:

env:
  VERSION_LABEL: v1.6.0
  VERSION_BRANCH: cm-reports-v160
  REQUIRED_LABEL: ready-to-merge

jobs:
  auto-merge-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI & dependencies
        run: |
          sudo apt update
          sudo apt install -y gh jq

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository (required for git merge)
        uses: actions/checkout@v4

      - name: Fetch all open PRs
        id: list-prs
        run: |
          prs=$(gh pr list --state open --json number | jq -r '.[].number')
          echo "PRS=$(echo "$prs" | tr '\n' ' ')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Process eligible PRs
        run: |
          for pr in $PRS; do
            echo "🔍 Checking PR #$pr..."

            base_branch=$(gh pr view $pr --json baseRefName --jq '.baseRefName')
            labels=$(gh pr view $pr --json labels --jq '.labels[].name')
            approved=$(gh pr view $pr --json reviewDecision --jq '.reviewDecision')
            resolved=$(gh pr view $pr --json reviewThreads --jq '[.reviewThreads[] | select(.isResolved == false)] | length == 0')
            mergeable=$(gh pr view $pr --json mergeable --jq '.mergeable')
            checks_passed=$(gh pr checks $pr --exit-status >/dev/null 2>&1 && echo true || echo false)

            echo "Base: $base_branch"
            echo "Labels: $labels"
            echo "Approved: $approved"
            echo "Resolved: $resolved"
            echo "Mergeable: $mergeable"
            echo "Checks Passed: $checks_passed"

            if [[ "$base_branch" != "$VERSION_BRANCH" ]]; then
              echo "⏩ Skipping: wrong base branch"
              continue
            fi

            if ! echo "$labels" | grep -q "$VERSION_LABEL"; then
              echo "⏩ Skipping: missing version label"
              continue
            fi

            if ! echo "$labels" | grep -q "$REQUIRED_LABEL"; then
              echo "⏩ Skipping: missing ready-to-merge label"
              continue
            fi

            if [[ "$approved" != "APPROVED" ]]; then
              echo "⏩ Skipping: not approved"
              continue
            fi

            if [[ "$resolved" != "true" ]]; then
              echo "⏩ Skipping: unresolved review threads"
              continue
            fi

            if [[ "$checks_passed" != "true" ]]; then
              echo "⏩ Skipping: CI failed or pending"
              continue
            fi

            if [[ "$mergeable" != "MERGEABLE" ]]; then
              echo "❌ Merge conflict detected. Skipping PR #$pr"
              continue
            fi

            echo "✅ PR #$pr is eligible. Updating branch with latest $VERSION_BRANCH..."

            gh pr checkout $pr
            git fetch origin $VERSION_BRANCH

            if ! git merge origin/$VERSION_BRANCH --no-edit; then
              echo "❌ Merge conflict when updating PR #$pr. Skipping."
              continue
            fi

            git push origin HEAD

            echo "🔀 Merging PR #$pr into $VERSION_BRANCH..."
            gh pr merge $pr --merge --delete-branch
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
